<a href="https://colab.research.google.com/github/jdpaezr/R1/blob/main/Data_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Data Manipulation

In [13]:
path= 'https://raw.githubusercontent.com/jdpaezr/R1/main/Datasets-main/datasets/Cartwheeldata.csv'

In [14]:
import pandas as pd

In [15]:
df = pd.read_csv(path)
df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56,F,1,Y,1,62.0,61.0,79,Y,1,7
1,2,26,F,1,Y,1,62.0,60.0,70,Y,1,8
2,3,33,F,1,Y,1,66.0,64.0,85,Y,1,0
3,4,39,F,1,N,0,64.0,63.0,87,Y,1,10
4,5,27,M,2,N,0,73.0,75.0,72,N,0,4

In [17]:
df.columns

Index(['ID', 'Age', 'Gender', 'GenderGroup', 'Glasses', 'GlassesGroup',
       'Height', 'Wingspan', 'CWDistance', 'Complete', 'CompleteGroup',
       'Score'],
      dtype='object')

In [19]:
nCls=df.columns.sort_values()
nCls

Index(['Age', 'CWDistance', 'Complete', 'CompleteGroup', 'Gender',
       'GenderGroup', 'Glasses', 'GlassesGroup', 'Height', 'ID', 'Score',
       'Wingspan'],
      dtype='object')

In [20]:
df.shape

(25, 12)

In [21]:
df.shape[0]

25

In [ ]:
ageData= df.Age
ageData

In [26]:
type(ageData)

pandas.core.series.Series

In [ ]:
ageData2=df['Age']
ageData2

In [ ]:
ageData3=df[['Age']]
ageData3

In [29]:
type(ageData3)

pandas.core.frame.DataFrame

In [ ]:
favs=['Age', 'Gender']
df[favs]

In [42]:
first4=df[['Age','Gender','GenderGroup','Glasses']]
first4

    Age Gender  GenderGroup Glasses
0    56      F            1       Y
1    26      F            1       Y
2    33      F            1       Y
3    39      F            1       N
4    27      M            2       N
5    24      M            2       N
6    28      M            2       N
7    22      F            1       N
8    29      M            2       Y
9    33      F            1       Y
10   30      M            2       Y
11   28      F            1       Y
12   25      F            1       Y
13   23      F            1       N
14   31      M            2       Y
15   26      M            2       Y
16   26      F            1       N
17   27      M            2       N
18   23      M            2       Y
19   24      F            1       Y
20   23      M            2       Y
21   29      M            2       N
22   25      M            2       N
23   26      M            2       N
24   23      F            1       Y

In [43]:
last4=df[['CWDistance', 'Complete', 'CompleteGroup','Score']]
last4

    CWDistance Complete  CompleteGroup  Score
0           79        Y              1      7
1           70        Y              1      8
2           85        Y              1      0
3           87        Y              1     10
4           72        N              0      4
5           81        N              0      3
6          107        Y              1     10
7           98        Y              1      9
8          106        N              0      5
9           65        Y              1      8
10          96        Y              1      6
11          79        Y              1     10
12          92        Y              1      6
13          66        Y              1      4
14          72        Y              1      9
15         115        Y              1      6
16          90        N              0     10
17          74        Y              1      5
18          64        Y              1      3
19          85        Y              1      8
20          66        N              0      2
21         101        Y              1      8
22          82        Y              1      4
23          63        Y              1      5
24          67        N              0      3

In [ ]:
specific=df[['Gender','GenderGroup','Glasses','Height','Complete']]
specific

In [45]:
#Para simploficar Codigo se usa loc(location) y iloc(index location).

#df.loc[row_name_start: row_name_end, column_name_stat:column_name_end]
#df.iloc[row_index_start: row_index_end, column_index_stat:column_index_end]

In [ ]:
df.loc[:,:'GenderGroup']

#row es de principio a fin por ende se ponen unicamente el doble punto para indicarlo. La columna es de principio
# hasta gender group por eso se define.

In [ ]:
df.iloc[:,:4]
#Para llamar las primeras 4 columnas de la base de datos.

In [53]:
df.iloc[:,-4:]
#Para llamar las ultimas 4 columnas de la base de datos

    CWDistance Complete  CompleteGroup  Score
0           79        Y              1      7
1           70        Y              1      8
2           85        Y              1      0
3           87        Y              1     10
4           72        N              0      4
5           81        N              0      3
6          107        Y              1     10
7           98        Y              1      9
8          106        N              0      5
9           65        Y              1      8
10          96        Y              1      6
11          79        Y              1     10
12          92        Y              1      6
13          66        Y              1      4
14          72        Y              1      9
15         115        Y              1      6
16          90        N              0     10
17          74        Y              1      5
18          64        Y              1      3
19          85        Y              1      8
20          66        N              0      2
21         101        Y              1      8
22          82        Y              1      4
23          63        Y              1      5
24          67        N              0      3

In [ ]:

df.iloc[5:11,[1,9]]
#Para llamar variables separadas con filas especificas

In [ ]:
df.loc[5:10,['Age','Complete']]
#Igual que la pasada pero con loc.

In [81]:
df.Gender.unique()
#Unqiue para checar valores unicos de la columna.

array(['F', 'M'], dtype=object)

In [83]:
df.Glasses.unique()

array(['Y', 'N'], dtype=object)

In [88]:
favs5=['Gender','Glasses']
df.groupby(favs5).size()

Gender  Glasses
F       N          4
        Y          8
M       N          7
        Y          6
dtype: int64

In [91]:
df[favs5].value_counts()

Gender  Glasses
F       Y          8
M       N          7
        Y          6
F       N          4
dtype: int64